---
driver:
  name: vagrant
  # without additional memory, ubuntu suites will fail
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    cassandra:
      cluster_name: test

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.4
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[cassandra::default]

  - name: opscenter-agent-datastax
    attributes:
      cassandra:
        opscenter:
          agent:
            server_host: 0.0.0.0
            use_chef_search: false
    run_list:
      - recipe[cassandra::default]
      - recipe[cassandra::opscenter_agent_datastax]

  - name: opscenter-server-datastax
    run_list:
      - recipe[cassandra::default]
      - recipe[cassandra::opscenter_server]

  - name: dsc21
    attributes:
      cassandra:
        package_name: dsc21
        version: 2.1.0
        release: 1
    run_list:
      - recipe[cassandra::default]

  - name: tarball
    run_list:
      - recipe[cassandra::tarball]

  - name: dse
    run_list:
      - recipe[cassandra::default]
    attributes:
      cassandra:
        dse:
          credentials:
            databag: false
            username: <%= ENV['CASSANDRA_DSE_USERNAME'] %>
            password: <%= ENV['CASSANDRA_DSE_PASSWORD'] %>
